# Generated by Django 4.1.4 on 2023-07-05 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='was_avilable',
            new_name='was_available',
        ),
        migrations.AddField(
            model_name='attendance',
            name='remark',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
